export const BUSY = "BUSY";
export const READY = "READY";
export const ERROR = "ERROR";

export const AUTH_LOG_IN = "AUTH_LOG_IN";
export const AUTH_LOG_OUT = "AUTH_LOG_OUT";
export const AUTH_BAD_CREDENTIALS = "AUTH_BAD_CREDENTIALS";
export const AUTH_BAD_CREDENTIALS_CLEAR = "AUTH_BAD_CREDENTIALS_CLEAR";

export const AUTH_STATE_LOAD = "AUTH_STATE_LOAD";
export const AUTH_STATE_SAVE = "AUTH_STATE_SAVE";
export const AUTH_STATE_CLEAR = "AUTH_STATE_CLEAR";

export const BAR_RECEIVE_LIST = "BAR_RECEIVE_LIST";
export const FOO_RECEIVE_LIST = "FOO_RECEIVE_LIST";
